// AUTO-GENERATED from github-linguist/languages.yml filtered to entries
// present in ozh/github-colors. Regenerate with scripts/gen_langmap.mjs.

use std::path::Path;

/// Look up an extension (without leading `.`, case-insensitive) in the
/// generated extension map. Uses binary search — the slice is sorted by key.
pub fn lookup_extension(ext: &str) -> Option<&'static str> {
    let lower = ext.to_ascii_lowercase();
    EXT_TO_LANG
        .binary_search_by_key(&lower.as_str(), |&(k, _)| k)
        .ok()
        .map(|i| EXT_TO_LANG[i].1)
}

/// Look up a basename (full filename, case-insensitive) in the generated
/// filename map. Covers extensionless files like `Dockerfile`, `Makefile`,
/// and lock/config files linguist recognizes by name.
pub fn lookup_basename(name: &str) -> Option<&'static str> {
    let lower = name.to_ascii_lowercase();
    NAME_TO_LANG
        .binary_search_by_key(&lower.as_str(), |&(k, _)| k)
        .ok()
        .map(|i| NAME_TO_LANG[i].1)
}

/// Resolve a file path to its language, checking basename first (so
/// `Dockerfile` / `Makefile` hit) and falling back to the extension.
pub fn language_for_path(path: &Path) -> Option<&'static str> {
    if let Some(name) = path.file_name().and_then(|s| s.to_str())
        && let Some(lang) = lookup_basename(name)
    {
        return Some(lang);
    }
    path.extension()
        .and_then(|s| s.to_str())
        .and_then(lookup_extension)
}

/// Allowlist of "main" programming languages the breakdown card will
/// surface — mirrors the list people mean when they say "what language
/// is this repo in?". Anything outside this set (data formats, prose,
/// configs, niche/legacy languages) is skipped so the UI shows real
/// code only. Grow the list cautiously; every addition bloats the
/// breakdown for ~every project that happens to have that extension.
pub fn is_main_language(lang: &str) -> bool {
    MAIN_LANGUAGES.contains(&lang)
}

const MAIN_LANGUAGES: &[&str] = &[
    // Web / frontend
    "JavaScript",
    "TypeScript",
    "HTML",
    "CSS",
    "SCSS",
    "Sass",
    "Less",
    "Stylus",
    "Vue",
    "Svelte",
    "Astro",
    "CoffeeScript",
    "LiveScript",
    // Systems
    "C",
    "C++",
    "C#",
    "Rust",
    "Go",
    "Zig",
    "Nim",
    "Crystal",
    "V",
    "D",
    "Carbon",
    "Mojo",
    // JVM
    "Java",
    "Kotlin",
    "Scala",
    "Groovy",
    "Clojure",
    // Scripting / dynamic
    "Python",
    "Ruby",
    "PHP",
    "Perl",
    "Lua",
    "Tcl",
    "R",
    "Julia",
    "MATLAB",
    "Dart",
    // Mobile / Apple
    "Swift",
    "Objective-C",
    "Objective-C++",
    // Functional
    "Haskell",
    "OCaml",
    "F#",
    "Elixir",
    "Erlang",
    "Elm",
    "Racket",
    "Scheme",
    "Common Lisp",
    "Emacs Lisp",
    // Shell / scripts
    "Shell",
    "Bash",
    "PowerShell",
    "Batchfile",
    "fish",
    // Database / query
    "SQL",
    "PLpgSQL",
    "PLSQL",
    "TSQL",
    "GraphQL",
    "Prisma",
    // Hardware / graphics
    "Assembly",
    "WebAssembly",
    "GLSL",
    "HLSL",
    "Metal",
    "Cuda",
    "OpenCL",
    "WGSL",
    "Verilog",
    "VHDL",
    "SystemVerilog",
    // Smart contracts
    "Solidity",
    "Vyper",
    "Move",
    "Cadence",
    "Clarity",
    // Build / infra code
    "Dockerfile",
    "Makefile",
    "CMake",
    "Meson",
    "HCL",
    "Starlark",
    // Legacy but still-written
    "Ada",
    "Fortran",
    "Fortran Free Form",
    "COBOL",
    "Visual Basic .NET",
    "VBA",
    "Pascal",
    // Templating / server pages
    "Handlebars",
    "Jinja",
    "EJS",
    "Pug",
    "Mustache",
    "Twig",
    "Liquid",
    "Blade",
    "ERB",
    // Misc popular
    "Vim Script",
    "Hack",
    "ReScript",
    "ReasonML",
    "PureScript",
    "Q#",
    "Apex",
    "JCL",
];

pub const EXT_TO_LANG: &[(&str, &str)] = &[
    ("_coffee", "CoffeeScript"),
    ("_js", "JavaScript"),
    ("_ls", "LiveScript"),
    ("1", "Roff Manpage"),
    ("1in", "Roff"),
    ("1m", "Roff"),
    ("1x", "Roff"),
    ("2", "Roff"),
    ("2da", "2-Dimensional Array"),
    ("3", "Roff"),
    ("3in", "Roff"),
    ("3m", "Roff"),
    ("3p", "Roff"),
    ("3pm", "Roff"),
    ("3qt", "Roff"),
    ("3x", "Roff"),
    ("4", "Roff"),
    ("4dform", "JSON"),
    ("4dm", "4D"),
    ("4dproject", "JSON"),
    ("4gl", "Genero 4gl"),
    ("4th", "Forth"),
    ("5", "Roff"),
    ("6", "Roff"),
    ("6pl", "Raku"),
    ("6pm", "Raku"),
    ("7", "Roff"),
    ("8", "Roff"),
    ("8xp", "TI Program"),
    ("8xp.txt", "TI Program"),
    ("9", "Roff"),
    ("a51", "Assembly"),
    ("abap", "ABAP"),
    ("action", "ROS Interface"),
    ("ada", "Ada"),
    ("adb", "Ada"),
    ("adml", "XML"),
    ("admx", "XML"),
    ("ado", "Stata"),
    ("adoc", "AsciiDoc"),
    ("adp", "Tcl"),
    ("ads", "Ada"),
    ("afm", "Adobe Font Metrics"),
    ("agc", "Apollo Guidance Computer"),
    ("agda", "Agda"),
    ("ahk", "AutoHotkey"),
    ("ahkl", "AutoHotkey"),
    ("aidl", "AIDL"),
    ("aj", "AspectJ"),
    ("ak", "Aiken"),
    ("al", "Perl"),
    ("alg", "ALGOL"),
    ("als", "Alloy"),
    ("ampl", "AMPL"),
    ("angelscript", "AngelScript"),
    ("anim", "Unity3D Asset"),
    ("ant", "XML"),
    ("antlers.html", "Antlers"),
    ("antlers.php", "Antlers"),
    ("antlers.xml", "Antlers"),
    ("apacheconf", "ApacheConf"),
    ("apex", "Apex"),
    ("apib", "API Blueprint"),
    ("apl", "APL"),
    ("app", "Erlang"),
    ("app.src", "Erlang"),
    ("applescript", "AppleScript"),
    ("arc", "Arc"),
    ("arr", "Pyret"),
    ("as", "ActionScript"),
    ("asax", "ASP.NET"),
    ("asc", "AGS Script"),
    ("asciidoc", "AsciiDoc"),
    ("ascx", "ASP.NET"),
    ("asd", "Common Lisp"),
    ("asddls", "ABAP CDS"),
    ("ash", "AGS Script"),
    ("ashx", "ASP.NET"),
    ("asm", "Assembly"),
    ("asmx", "ASP.NET"),
    ("asp", "Classic ASP"),
    ("aspx", "ASP.NET"),
    ("asset", "Unity3D Asset"),
    ("astro", "Astro"),
    ("asy", "Asymptote"),
    ("au3", "AutoIt"),
    ("aug", "Augeas"),
    ("auk", "Awk"),
    ("aux", "TeX"),
    ("avdl", "Avro IDL"),
    ("avsc", "JSON"),
    ("aw", "PHP"),
    ("awk", "Awk"),
    ("axaml", "XML"),
    ("axd", "ASP.NET"),
    ("axi", "NetLinx"),
    ("axi.erb", "NetLinx+ERB"),
    ("axml", "XML"),
    ("axs", "NetLinx"),
    ("axs.erb", "NetLinx+ERB"),
    ("b", "Brainfuck"),
    ("bal", "Ballerina"),
    ("bas", "B4X"),
    ("bash", "Shell"),
    ("bat", "Batchfile"),
    ("bats", "Shell"),
    ("bb", "Clojure"),
    ("bbappend", "BitBake"),
    ("bbclass", "BitBake"),
    ("bbx", "TeX"),
    ("bdy", "PLSQL"),
    ("be", "Berry"),
    ("bf", "Beef"),
    ("bi", "FreeBASIC"),
    ("bib", "BibTeX"),
    ("bibtex", "BibTeX"),
    ("bicep", "Bicep"),
    ("bicepparam", "Bicep"),
    ("bison", "Bison"),
    ("blade", "Blade"),
    ("blade.php", "Blade"),
    ("bmx", "BlitzMax"),
    ("bones", "JavaScript"),
    ("boo", "Boo"),
    ("boot", "Clojure"),
    ("bpl", "Boogie"),
    ("bqn", "BQN"),
    ("brd", "KiCad Legacy Layout"),
    ("brs", "Brightscript"),
    ("bru", "Bru"),
    ("bs", "Bikeshed"),
    ("bsl", "1C Enterprise"),
    ("bst", "BuildStream"),
    ("bsv", "Bluespec"),
    ("builder", "Ruby"),
    ("builds", "XML"),
    ("bzl", "Starlark"),
    ("c", "C"),
    ("c++", "C++"),
    ("c3", "C3"),
    ("cabal", "Cabal Config"),
    ("caddyfile", "Caddyfile"),
    ("cairo", "Cairo"),
    ("cake", "C#"),
    ("capnp", "Cap'n Proto"),
    ("carbon", "Carbon"),
    ("cats", "C"),
    ("cbx", "TeX"),
    ("cc", "C++"),
    ("ccproj", "XML"),
    ("ccxml", "XML"),
    ("cdc", "Cadence"),
    ("cdf", "Wolfram Language"),
    ("cds", "CAP CDS"),
    ("ceylon", "Ceylon"),
    ("cfc", "ColdFusion CFC"),
    ("cfg", "HAProxy"),
    ("cfm", "ColdFusion"),
    ("cfml", "ColdFusion"),
    ("cgi", "Python"),
    ("cginc", "HLSL"),
    ("ch", "xBase"),
    ("chpl", "Chapel"),
    ("circom", "Circom"),
    ("cirru", "Cirru"),
    ("cj", "Cangjie"),
    ("cjs", "JavaScript"),
    ("cjsx", "CoffeeScript"),
    ("ck", "ChucK"),
    ("cl", "Common Lisp"),
    ("cl2", "Clojure"),
    ("clar", "Clarity"),
    ("click", "Click"),
    ("clixml", "XML"),
    ("clj", "Clojure"),
    ("cljc", "Clojure"),
    ("cljs", "Clojure"),
    ("cljs.hl", "Clojure"),
    ("cljscm", "Clojure"),
    ("cljx", "Clojure"),
    ("clp", "CLIPS"),
    ("cls", "Apex"),
    ("clue", "Clue"),
    ("clw", "Clarion"),
    ("cmake", "CMake"),
    ("cmake.in", "CMake"),
    ("cmd", "Batchfile"),
    ("cmp", "Gerber Image"),
    ("cnc", "G-code"),
    ("cnf", "INI"),
    ("cocci", "SmPL"),
    ("code-snippets", "JSON with Comments"),
    ("code-workspace", "JSON with Comments"),
    ("coffee", "CoffeeScript"),
    ("coffee.md", "Literate CoffeeScript"),
    ("command", "Shell"),
    ("containerfile", "Dockerfile"),
    ("cook", "Cooklang"),
    ("coq", "Rocq Prover"),
    ("cp", "C++"),
    ("cpp", "C++"),
    ("cppm", "C++"),
    ("cproject", "XML"),
    ("cps", "Component Pascal"),
    ("cql", "CQL"),
    ("cr", "Crystal"),
    ("cs", "C#"),
    ("cs.pp", "C#"),
    ("csc", "GSC"),
    ("cscfg", "XML"),
    ("csd", "Csound Document"),
    ("csdef", "XML"),
    ("cshtml", "HTML+Razor"),
    ("csl", "XML"),
    ("cson", "CSON"),
    ("csproj", "XML"),
    ("css", "CSS"),
    ("csv", "CSV"),
    ("csx", "C#"),
    ("ct", "XML"),
    ("ctl", "Visual Basic 6.0"),
    ("ctp", "PHP"),
    ("cts", "TypeScript"),
    ("cu", "Cuda"),
    ("cue", "CUE"),
    ("cuh", "Cuda"),
    ("curry", "Curry"),
    ("cwl", "Common Workflow Language"),
    ("cxx", "C++"),
    ("cylc", "Cylc"),
    ("cyp", "Cypher"),
    ("cypher", "Cypher"),
    ("d", "D"),
    ("d2", "D2"),
    ("dae", "COLLADA"),
    ("darcspatch", "Darcs Patch"),
    ("dart", "Dart"),
    ("das", "Daslang"),
    ("dats", "ATS"),
    ("db2", "SQLPL"),
    ("dcl", "Clean"),
    ("ddl", "SQL"),
    ("decls", "BlitzBasic"),
    ("depproj", "XML"),
    ("dfm", "Pascal"),
    ("dfy", "Dafny"),
    ("dhall", "Dhall"),
    ("di", "D"),
    ("dita", "XML"),
    ("ditamap", "XML"),
    ("ditaval", "XML"),
    ("djs", "Dogescript"),
    ("dll.config", "XML"),
    ("dlm", "IDL"),
    ("dm", "DM"),
    ("do", "Stata"),
    ("dockerfile", "Dockerfile"),
    ("dof", "INI"),
    ("doh", "Stata"),
    ("dot", "Graphviz (DOT)"),
    ("dotsettings", "XML"),
    ("dpatch", "Darcs Patch"),
    ("dpr", "Pascal"),
    ("druby", "Mirah"),
    ("dsc", "Debian Package Control File"),
    ("dsp", "Faust"),
    ("dsr", "Visual Basic 6.0"),
    ("dtx", "TeX"),
    ("duby", "Mirah"),
    ("dwl", "DataWeave"),
    ("dyalog", "APL"),
    ("dyl", "Dylan"),
    ("dylan", "Dylan"),
    ("e", "E"),
    ("eb", "Easybuild"),
    ("ebuild", "Gentoo Ebuild"),
    ("ec", "eC"),
    ("ecl", "ECL"),
    ("eclass", "Gentoo Eclass"),
    ("eclxml", "ECL"),
    ("ecr", "HTML+ECR"),
    ("ect", "EJS"),
    ("edge", "Edge"),
    ("edgeql", "EdgeQL"),
    ("editorconfig", "EditorConfig"),
    ("eh", "eC"),
    ("ejs", "EJS"),
    ("ejs.t", "EJS"),
    ("el", "Emacs Lisp"),
    ("eliom", "OCaml"),
    ("eliomi", "OCaml"),
    ("elm", "Elm"),
    ("elv", "Elvish"),
    ("em", "EmberScript"),
    ("emacs", "Emacs Lisp"),
    ("emacs.desktop", "Emacs Lisp"),
    ("emberscript", "EmberScript"),
    ("env", "Dotenv"),
    ("epj", "Ecere Projects"),
    ("eps", "PostScript"),
    ("epsi", "PostScript"),
    ("eq", "EQ"),
    ("erb", "HTML+ERB"),
    ("erb.deface", "HTML+ERB"),
    ("erl", "Erlang"),
    ("es", "JavaScript"),
    ("es6", "JavaScript"),
    ("escript", "Erlang"),
    ("esdl", "EdgeQL"),
    ("ex", "Elixir"),
    ("exs", "Elixir"),
    ("eye", "Ruby"),
    ("f", "Filebench WML"),
    ("f03", "Fortran Free Form"),
    ("f08", "Fortran Free Form"),
    ("f77", "Fortran"),
    ("f90", "Fortran Free Form"),
    ("f95", "Fortran Free Form"),
    ("factor", "Factor"),
    ("fan", "Fantom"),
    ("fancypack", "Fancy"),
    ("fbs", "FlatBuffers"),
    ("fcgi", "Python"),
    ("feature", "Gherkin"),
    ("filters", "XML"),
    ("fir", "FIRRTL"),
    ("fish", "fish"),
    ("flex", "JFlex"),
    ("flf", "FIGlet Font"),
    ("flix", "Flix"),
    ("flux", "FLUX"),
    ("fnc", "PLSQL"),
    ("fnl", "Fennel"),
    ("for", "Forth"),
    ("forth", "Forth"),
    ("fp", "GLSL"),
    ("fpp", "Fortran"),
    ("fr", "Frege"),
    ("frag", "JavaScript"),
    ("frg", "GLSL"),
    ("frm", "INI"),
    ("frt", "Forth"),
    ("fs", "F#"),
    ("fsh", "GLSL"),
    ("fshader", "GLSL"),
    ("fsi", "F#"),
    ("fsproj", "XML"),
    ("fst", "F*"),
    ("fsti", "F*"),
    ("fsx", "F#"),
    ("fth", "Forth"),
    ("ftl", "Fluent"),
    ("ftlh", "FreeMarker"),
    ("fun", "Standard ML"),
    ("fut", "Futhark"),
    ("fx", "FLUX"),
    ("fxh", "HLSL"),
    ("fxml", "XML"),
    ("fy", "Fancy"),
    ("g", "G-code"),
    ("g4", "ANTLR"),
    ("gaml", "GAML"),
    ("gap", "GAP"),
    ("gawk", "Awk"),
    ("gbl", "Gerber Image"),
    ("gbo", "Gerber Image"),
    ("gbp", "Gerber Image"),
    ("gbr", "Gerber Image"),
    ("gbs", "Gerber Image"),
    ("gco", "G-code"),
    ("gcode", "G-code"),
    ("gd", "GDScript"),
    ("gdnlib", "Godot Resource"),
    ("gdns", "Godot Resource"),
    ("gdshader", "GDShader"),
    ("gdshaderinc", "GDShader"),
    ("ged", "GEDCOM"),
    ("gemspec", "Ruby"),
    ("geo", "GLSL"),
    ("geojson", "JSON"),
    ("geom", "GLSL"),
    ("gf", "Grammatical Framework"),
    ("gi", "GAP"),
    ("gitconfig", "Git Config"),
    ("gitignore", "Ignore List"),
    ("gjs", "Glimmer JS"),
    ("gko", "Gerber Image"),
    ("glade", "XML"),
    ("gleam", "Gleam"),
    ("glf", "Glyph"),
    ("glsl", "GLSL"),
    ("glslf", "GLSL"),
    ("glslv", "GLSL"),
    ("gltf", "JSON"),
    ("gmi", "Gemini"),
    ("gml", "XML"),
    ("gms", "GAMS"),
    ("gmx", "XML"),
    ("gnu", "Gnuplot"),
    ("gnuplot", "Gnuplot"),
    ("go", "Go"),
    ("god", "Ruby"),
    ("gohtml", "Go Template"),
    ("golo", "Golo"),
    ("gotmpl", "Go Template"),
    ("gp", "Gnuplot"),
    ("gpb", "Gerber Image"),
    ("gpt", "Gerber Image"),
    ("gpx", "XML"),
    ("gql", "GraphQL"),
    ("grace", "Grace"),
    ("gradle", "Gradle"),
    ("gradle.kts", "Gradle Kotlin DSL"),
    ("graphql", "GraphQL"),
    ("graphqls", "GraphQL"),
    ("groovy", "Groovy"),
    ("grt", "Groovy"),
    ("grxml", "XML"),
    ("gs", "JavaScript"),
    ("gsc", "GSC"),
    ("gsh", "GSC"),
    ("gshader", "GLSL"),
    ("gsp", "Groovy Server Pages"),
    ("gst", "XML"),
    ("gsx", "Gosu"),
    ("gtl", "Gerber Image"),
    ("gto", "Gerber Image"),
    ("gtp", "Gerber Image"),
    ("gtpl", "Groovy"),
    ("gts", "Glimmer TS"),
    ("gv", "Graphviz (DOT)"),
    ("gvy", "Groovy"),
    ("gyp", "Python"),
    ("gypi", "Python"),
    ("h", "C"),
    ("h.in", "C"),
    ("h++", "C++"),
    ("ha", "Hare"),
    ("hack", "Hack"),
    ("haml", "Haml"),
    ("haml.deface", "Haml"),
    ("handlebars", "Handlebars"),
    ("har", "JSON"),
    ("hats", "ATS"),
    ("hb", "Harbour"),
    ("hbs", "Handlebars"),
    ("hc", "HolyC"),
    ("hcl", "HCL"),
    ("heex", "HTML+EEX"),
    ("hh", "C++"),
    ("hhi", "Hack"),
    ("hic", "Clojure"),
    ("hip", "HIP"),
    ("hlsl", "HLSL"),
    ("hlsli", "HLSL"),
    ("hocon", "HOCON"),
    ("hoon", "hoon"),
    ("hpp", "C++"),
    ("hqf", "SQF"),
    ("hql", "HiveQL"),
    ("hrl", "Erlang"),
    ("hs", "Haskell"),
    ("hs-boot", "Haskell"),
    ("hsc", "Haskell"),
    ("hta", "HTML"),
    ("htm", "HTML"),
    ("html", "HTML"),
    ("html.eex", "HTML+EEX"),
    ("html.hl", "HTML"),
    ("html.tmpl", "Go Template"),
    ("http", "HTTP"),
    ("hurl", "Hurl"),
    ("hx", "Haxe"),
    ("hxml", "HXML"),
    ("hxsl", "Haxe"),
    ("hxx", "C++"),
    ("hy", "Hy"),
    ("hzp", "XML"),
    ("i", "Assembly"),
    ("i3", "Modula-3"),
    ("ical", "iCalendar"),
    ("ice", "JSON"),
    ("iced", "CoffeeScript"),
    ("icl", "Clean"),
    ("icls", "XML"),
    ("ics", "iCalendar"),
    ("idc", "C"),
    ("idr", "Idris"),
    ("ig", "Modula-3"),
    ("ihlp", "Stata"),
    ("ijm", "ImageJ Macro"),
    ("ijs", "J"),
    ("ik", "Ioke"),
    ("ily", "LilyPond"),
    ("imba", "Imba"),
    ("iml", "XML"),
    ("inc", "C++"),
    ("ini", "INI"),
    ("inl", "C++"),
    ("ino", "C++"),
    ("ins", "TeX"),
    ("intr", "Dylan"),
    ("io", "Io"),
    ("iol", "Jolie"),
    ("ipf", "IGOR Pro"),
    ("ipp", "C++"),
    ("ipynb", "Jupyter Notebook"),
    ("isl", "Inno Setup"),
    ("ispc", "ISPC"),
    ("iss", "Inno Setup"),
    ("iuml", "PlantUML"),
    ("ivy", "XML"),
    ("ixx", "C++"),
    ("j", "Jasmin"),
    ("j2", "Jinja"),
    ("jac", "Jac"),
    ("jade", "Pug"),
    ("jai", "Jai"),
    ("jake", "JavaScript"),
    ("janet", "Janet"),
    ("jav", "Java"),
    ("java", "Java"),
    ("javascript", "JavaScript"),
    ("jbuilder", "Ruby"),
    ("jcl", "JCL"),
    ("jelly", "XML"),
    ("jflex", "JFlex"),
    ("jinja", "Jinja"),
    ("jinja2", "Jinja"),
    ("jison", "Jison"),
    ("jisonlex", "Jison Lex"),
    ("jl", "Julia"),
    ("jq", "JSONiq"),
    ("js", "JavaScript"),
    ("js.erb", "JavaScript+ERB"),
    ("jsb", "JavaScript"),
    ("jscad", "JavaScript"),
    ("jsfl", "JavaScript"),
    ("jsh", "Java"),
    ("jslib", "JavaScript"),
    ("jsm", "JavaScript"),
    ("json", "JSON"),
    ("json-tmlanguage", "JSON"),
    ("json.example", "JSON"),
    ("json5", "JSON5"),
    ("jsonc", "JSON with Comments"),
    ("jsonl", "JSON"),
    ("jsonld", "JSONLD"),
    ("jsonnet", "Jsonnet"),
    ("jsp", "Java Server Pages"),
    ("jspre", "JavaScript"),
    ("jsproj", "XML"),
    ("jss", "JavaScript"),
    ("jst", "EJS"),
    ("jsx", "JavaScript"),
    ("jte", "Java Template Engine"),
    ("just", "Just"),
    ("k", "KCL"),
    ("kak", "KakouneScript"),
    ("kdl", "KDL"),
    ("kicad_mod", "KiCad Layout"),
    ("kicad_pcb", "KiCad Layout"),
    ("kicad_sch", "KiCad Schematic"),
    ("kicad_sym", "KiCad Schematic"),
    ("kicad_wks", "KiCad Layout"),
    ("kid", "Genshi"),
    ("kk", "Koka"),
    ("kml", "XML"),
    ("kojo", "Scala"),
    ("krl", "KRL"),
    ("ks", "KerboScript"),
    ("ksh", "Shell"),
    ("ksy", "Kaitai Struct"),
    ("kt", "Kotlin"),
    ("ktm", "Kotlin"),
    ("kts", "Kotlin"),
    ("kv", "kvlang"),
    ("l", "Common Lisp"),
    ("lagda", "Literate Agda"),
    ("langium", "Langium"),
    ("lark", "Lark"),
    ("las", "Lasso"),
    ("lasso", "Lasso"),
    ("lasso8", "Lasso"),
    ("lasso9", "Lasso"),
    ("latte", "Latte"),
    ("launch", "XML"),
    ("lbx", "TeX"),
    ("leex", "HTML+EEX"),
    ("lektorproject", "INI"),
    ("leo", "Leo"),
    ("less", "Less"),
    ("lex", "Lex"),
    ("lfe", "LFE"),
    ("lgt", "Logtalk"),
    ("lhs", "Literate Haskell"),
    ("libsonnet", "Jsonnet"),
    ("lid", "Dylan"),
    ("lidr", "Idris"),
    ("ligo", "LigoLANG"),
    ("linq", "C#"),
    ("liq", "Liquidsoap"),
    ("liquid", "Liquid"),
    ("lisp", "Common Lisp"),
    ("litcoffee", "Literate CoffeeScript"),
    ("livecodescript", "LiveCode Script"),
    ("livemd", "Markdown"),
    ("lkml", "LookML"),
    ("ll", "LLVM"),
    ("lmi", "Python"),
    ("logtalk", "Logtalk"),
    ("lol", "LOLCODE"),
    ("lookml", "LookML"),
    ("lp", "Answer Set Programming"),
    ("lpr", "Pascal"),
    ("ls", "LiveScript"),
    ("lsl", "LSL"),
    ("lslp", "LSL"),
    ("lsp", "Common Lisp"),
    ("ltx", "TeX"),
    ("lua", "Lua"),
    ("luau", "Luau"),
    ("lvclass", "LabVIEW"),
    ("lvlib", "LabVIEW"),
    ("lvproj", "LabVIEW"),
    ("ly", "LilyPond"),
    ("m", "Objective-C"),
    ("m2", "Macaulay2"),
    ("m3", "Modula-3"),
    ("m3u", "M3U"),
    ("m3u8", "M3U"),
    ("ma", "Wolfram Language"),
    ("mak", "Makefile"),
    ("make", "Makefile"),
    ("makefile", "Makefile"),
    ("mako", "Mako"),
    ("man", "Roff"),
    ("mao", "Mako"),
    ("markdown", "Markdown"),
    ("marko", "Marko"),
    ("mask", "Mask"),
    ("mat", "Unity3D Asset"),
    ("mata", "Stata"),
    ("matah", "Stata"),
    ("mathematica", "Wolfram Language"),
    ("matlab", "MATLAB"),
    ("mawk", "Awk"),
    ("maxhelp", "Max"),
    ("maxpat", "Max"),
    ("maxproj", "Max"),
    ("mbt", "MoonBit"),
    ("mc", "Monkey C"),
    ("mcfunction", "mcfunction"),
    ("mch", "B (Formal Method)"),
    ("mcmeta", "JSON"),
    ("mcr", "MAXScript"),
    ("md", "Markdown"),
    ("mdoc", "Roff"),
    ("mdown", "Markdown"),
    ("mdpolicy", "XML"),
    ("mdwn", "Markdown"),
    ("mdx", "MDX"),
    ("me", "Roff"),
    ("mediawiki", "Wikitext"),
    ("mermaid", "Mermaid"),
    ("meta", "Unity3D Asset"),
    ("metal", "Metal"),
    ("metta", "MeTTa"),
    ("mg", "Modula-3"),
    ("mint", "Mint"),
    ("mir", "YAML"),
    ("mirah", "Mirah"),
    ("mjml", "XML"),
    ("mjs", "JavaScript"),
    ("mk", "Makefile"),
    ("mkd", "Markdown"),
    ("mkdn", "Markdown"),
    ("mkdown", "Markdown"),
    ("mkfile", "Makefile"),
    ("mkii", "TeX"),
    ("mkiv", "TeX"),
    ("mkvi", "TeX"),
    ("ml", "OCaml"),
    ("ml4", "OCaml"),
    ("mli", "OCaml"),
    ("mligo", "CameLIGO"),
    ("mlir", "MLIR"),
    ("mll", "OCaml"),
    ("mly", "OCaml"),
    ("mm", "XML"),
    ("mmd", "Mermaid"),
    ("mo", "Modelica"),
    ("mod", "XML"),
    ("mojo", "XML"),
    ("moo", "Mercury"),
    ("moon", "MoonScript"),
    ("move", "Move"),
    ("mpl", "JetBrains MPS"),
    ("mps", "JetBrains MPS"),
    ("mq4", "MQL4"),
    ("mq5", "MQL5"),
    ("mqh", "MQL4"),
    ("mrc", "mIRC Script"),
    ("ms", "MAXScript"),
    ("msd", "JetBrains MPS"),
    ("msg", "OMNeT++ MSG"),
    ("mspec", "Ruby"),
    ("mt", "Wolfram Language"),
    ("mtml", "MTML"),
    ("mts", "TypeScript"),
    ("mu", "mupad"),
    ("mud", "ZIL"),
    ("mustache", "Mustache"),
    ("mxml", "XML"),
    ("mxt", "Max"),
    ("mysql", "SQL"),
    ("mzn", "MiniZinc"),
    ("n", "Nemerle"),
    ("nanorc", "nanorc"),
    ("nas", "Assembly"),
    ("nasm", "Assembly"),
    ("natvis", "XML"),
    ("nawk", "Awk"),
    ("nb", "Wolfram Language"),
    ("nbp", "Wolfram Language"),
    ("nc", "nesC"),
    ("ncl", "XML"),
    ("ndproj", "XML"),
    ("ne", "Nearley"),
    ("nearley", "Nearley"),
    ("ned", "OMNeT++ NED"),
    ("nf", "Nextflow"),
    ("nginx", "Nginx"),
    ("nginxconf", "Nginx"),
    ("nim", "Nim"),
    ("nim.cfg", "Nim"),
    ("nimble", "Nim"),
    ("nimrod", "Nim"),
    ("nims", "Nim"),
    ("nit", "Nit"),
    ("nix", "Nix"),
    ("njk", "Nunjucks"),
    ("njs", "JavaScript"),
    ("nl", "NewLisp"),
    ("nlogo", "NetLogo"),
    ("nomad", "HCL"),
    ("nproj", "XML"),
    ("nqp", "Raku"),
    ("nr", "Noir"),
    ("nse", "Lua"),
    ("nss", "NWScript"),
    ("nu", "Nu"),
    ("numpy", "NumPy"),
    ("numpyw", "NumPy"),
    ("numsc", "NumPy"),
    ("nuspec", "XML"),
    ("nut", "Squirrel"),
    ("ny", "Common Lisp"),
    ("odd", "XML"),
    ("odin", "Odin"),
    ("ol", "Jolie"),
    ("omgrofl", "Omgrofl"),
    ("ooc", "ooc"),
    ("opal", "Opal"),
    ("opencl", "OpenCL"),
    ("orc", "Csound"),
    ("org", "Org"),
    ("os", "1C Enterprise"),
    ("osm", "XML"),
    ("outjob", "Altium Designer"),
    ("overpassql", "OverpassQL"),
    ("owl", "Web Ontology Language"),
    ("oxygene", "Oxygene"),
    ("oz", "Oz"),
    ("p", "Gnuplot"),
    ("p4", "P4"),
    ("p6", "Raku"),
    ("p6l", "Raku"),
    ("p6m", "Raku"),
    ("p8", "Lua"),
    ("pac", "JavaScript"),
    ("pact", "Pact"),
    ("pan", "Pan"),
    ("parrot", "Parrot"),
    ("pas", "Pascal"),
    ("pascal", "Pascal"),
    ("pat", "Max"),
    ("pb", "PureBasic"),
    ("pbi", "PureBasic"),
    ("pbt", "PowerBuilder"),
    ("pcbdoc", "Altium Designer"),
    ("pck", "PLSQL"),
    ("pcss", "PostCSS"),
    ("pd_lua", "Lua"),
    ("pddl", "PDDL"),
    ("pde", "Processing"),
    ("peggy", "PEG.js"),
    ("pegjs", "PEG.js"),
    ("pep", "Pep8"),
    ("per", "Genero per"),
    ("perl", "Perl"),
    ("pfa", "PostScript"),
    ("pgsql", "PLpgSQL"),
    ("ph", "Perl"),
    ("php", "PHP"),
    ("php3", "PHP"),
    ("php4", "PHP"),
    ("php5", "PHP"),
    ("phps", "PHP"),
    ("phpt", "PHP"),
    ("phtml", "HTML+PHP"),
    ("pig", "PigLatin"),
    ("pike", "Pike"),
    ("pkb", "PLSQL"),
    ("pkgproj", "XML"),
    ("pkl", "Pkl"),
    ("pks", "PLSQL"),
    ("pl", "Perl"),
    ("pl6", "Raku"),
    ("plantuml", "PlantUML"),
    ("plb", "PLSQL"),
    ("plist", "XML Property List"),
    ("plot", "Gnuplot"),
    ("pls", "PLSQL"),
    ("plsql", "PLSQL"),
    ("plt", "Gnuplot"),
    ("pluginspec", "Ruby"),
    ("plx", "Perl"),
    ("pm", "Perl"),
    ("pm6", "Raku"),
    ("pml", "Promela"),
    ("pmod", "Pike"),
    ("podsl", "Common Lisp"),
    ("podspec", "Ruby"),
    ("pogo", "PogoScript"),
    ("polar", "Polar"),
    ("por", "Portugol"),
    ("postcss", "PostCSS"),
    ("pov", "POV-Ray SDL"),
    ("pp", "Puppet"),
    ("pprx", "REXX"),
    ("praat", "Praat"),
    ("prawn", "Ruby"),
    ("prc", "SQL"),
    ("prefab", "Unity3D Asset"),
    ("prefs", "INI"),
    ("prg", "xBase"),
    ("prisma", "Prisma"),
    ("prjpcb", "Altium Designer"),
    ("pro", "IDL"),
    ("proj", "XML"),
    ("prolog", "Prolog"),
    ("properties", "INI"),
    ("props", "XML"),
    ("prw", "xBase"),
    ("ps", "PostScript"),
    ("ps1", "PowerShell"),
    ("ps1xml", "XML"),
    ("psc", "Papyrus"),
    ("psc1", "XML"),
    ("psd1", "PowerShell"),
    ("psgi", "Perl"),
    ("psm1", "PowerShell"),
    ("pt", "XML"),
    ("pubxml", "XML"),
    ("pug", "Pug"),
    ("puml", "PlantUML"),
    ("purs", "PureScript"),
    ("pwn", "Pawn"),
    ("pxd", "Cython"),
    ("pxi", "Cython"),
    ("py", "Python"),
    ("py3", "Python"),
    ("pyde", "Python"),
    ("pyi", "Python"),
    ("pyp", "Python"),
    ("pyt", "Python"),
    ("pytb", "Python traceback"),
    ("pyw", "Python"),
    ("pyx", "Cython"),
    ("q", "HiveQL"),
    ("qasm", "OpenQASM"),
    ("qbs", "QML"),
    ("qc", "QuakeC"),
    ("qhelp", "XML"),
    ("ql", "CodeQL"),
    ("qll", "CodeQL"),
    ("qmd", "RMarkdown"),
    ("qml", "QML"),
    ("qs", "Q#"),
    ("r", "R"),
    ("r2", "Rebol"),
    ("r3", "Rebol"),
    ("rabl", "Ruby"),
    ("rake", "Ruby"),
    ("raku", "Raku"),
    ("rakumod", "Raku"),
    ("raml", "RAML"),
    ("rascript", "RAScript"),
    ("razor", "HTML+Razor"),
    ("rb", "Ruby"),
    ("rbi", "Ruby"),
    ("rbs", "RBS"),
    ("rbuild", "Ruby"),
    ("rbw", "Ruby"),
    ("rbx", "Ruby"),
    ("rbxs", "Lua"),
    ("rchit", "GLSL"),
    ("rd", "R"),
    ("rdf", "XML"),
    ("rdoc", "RDoc"),
    ("re", "C++"),
    ("reb", "Rebol"),
    ("rebol", "Rebol"),
    ("red", "Red"),
    ("reds", "Red"),
    ("reek", "YAML"),
    ("reg", "Windows Registry Entries"),
    ("regex", "Regular Expression"),
    ("regexp", "Regular Expression"),
    ("rego", "Open Policy Agent"),
    ("rei", "Reason"),
    ("religo", "ReasonLIGO"),
    ("res", "XML"),
    ("resi", "ReScript"),
    ("resource", "RobotFramework"),
    ("rest", "reStructuredText"),
    ("rest.txt", "reStructuredText"),
    ("resx", "XML"),
    ("rex", "REXX"),
    ("rexx", "REXX"),
    ("rg", "Rouge"),
    ("rhtml", "HTML+ERB"),
    ("ring", "Ring"),
    ("riot", "Riot"),
    ("rkt", "Racket"),
    ("rktd", "Racket"),
    ("rktl", "Racket"),
    ("rl", "Ragel"),
    ("rmd", "RMarkdown"),
    ("rmiss", "GLSL"),
    ("rnh", "RUNOFF"),
    ("rno", "Roff"),
    ("rnw", "Sweave"),
    ("robot", "RobotFramework"),
    ("roc", "Roc"),
    ("rockspec", "Lua"),
    ("roff", "Roff"),
    ("ron", "RON"),
    ("ronn", "Markdown"),
    ("rpgle", "RPGLE"),
    ("rpy", "Python"),
    ("rq", "SPARQL"),
    ("rs", "Rust"),
    ("rs.in", "Rust"),
    ("rsc", "Rascal"),
    ("rss", "XML"),
    ("rst", "reStructuredText"),
    ("rst.txt", "reStructuredText"),
    ("rsx", "R"),
    ("ru", "Ruby"),
    ("ruby", "Ruby"),
    ("rviz", "YAML"),
    ("s", "Assembly"),
    ("sail", "Sail"),
    ("sarif", "JSON"),
    ("sas", "SAS"),
    ("sass", "Sass"),
    ("sats", "ATS"),
    ("sbatch", "Shell"),
    ("sbt", "Scala"),
    ("sc", "Scala"),
    ("scad", "OpenSCAD"),
    ("scala", "Scala"),
    ("scaml", "Scaml"),
    ("scd", "Markdown"),
    ("sce", "Scilab"),
    ("scenic", "Scenic"),
    ("sch", "XML"),
    ("schdoc", "Altium Designer"),
    ("sci", "Scilab"),
    ("scm", "Scheme"),
    ("sco", "Csound Score"),
    ("scpt", "AppleScript"),
    ("scrbl", "Racket"),
    ("scss", "SCSS"),
    ("scxml", "XML"),
    ("sdc", "Tcl"),
    ("sed", "sed"),
    ("self", "Self"),
    ("sexp", "Common Lisp"),
    ("sfproj", "XML"),
    ("sfv", "Simple File Verification"),
    ("sh", "Shell"),
    ("sh.in", "Shell"),
    ("shader", "GLSL"),
    ("shen", "Shen"),
    ("shproj", "XML"),
    ("sig", "Standard ML"),
    ("sj", "Objective-J"),
    ("sjs", "JavaScript"),
    ("sl", "Slash"),
    ("slang", "Slang"),
    ("sld", "Scheme"),
    ("slim", "Slim"),
    ("slint", "Slint"),
    ("slnx", "XML"),
    ("sls", "SaltStack"),
    ("slurm", "Shell"),
    ("sma", "Pawn"),
    ("smithy", "Smithy"),
    ("smk", "Snakemake"),
    ("sml", "Standard ML"),
    ("snakefile", "Snakemake"),
    ("snap", "Jest Snapshot"),
    ("snip", "Vim Snippet"),
    ("snippet", "Vim Snippet"),
    ("snippets", "Vim Snippet"),
    ("sol", "Solidity"),
    ("soy", "Closure Templates"),
    ("sp", "SourcePawn"),
    ("sparql", "SPARQL"),
    ("spc", "PLSQL"),
    ("spec", "Python"),
    ("spin", "Propeller Spin"),
    ("sps", "Scheme"),
    ("sqf", "SQF"),
    ("sql", "SQL"),
    ("sqlrpgle", "RPGLE"),
    ("sra", "PowerBuilder"),
    ("srdf", "XML"),
    ("srt", "SRecode Template"),
    ("sru", "PowerBuilder"),
    ("srv", "ROS Interface"),
    ("srw", "PowerBuilder"),
    ("ss", "Scheme"),
    ("ssjs", "JavaScript"),
    ("sss", "SugarSS"),
    ("st", "Smalltalk"),
    ("stan", "Stan"),
    ("star", "Starlark"),
    ("sthlp", "Stata"),
    ("stl", "STL"),
    ("story", "Gherkin"),
    ("storyboard", "XML"),
    ("sttheme", "XML Property List"),
    ("sty", "TeX"),
    ("styl", "Stylus"),
    ("sublime_metrics", "JSON with Comments"),
    ("sublime_session", "JSON with Comments"),
    ("sublime-build", "JSON with Comments"),
    ("sublime-color-scheme", "JSON with Comments"),
    ("sublime-commands", "JSON with Comments"),
    ("sublime-completions", "JSON with Comments"),
    ("sublime-keymap", "JSON with Comments"),
    ("sublime-macro", "JSON with Comments"),
    ("sublime-menu", "JSON with Comments"),
    ("sublime-mousemap", "JSON with Comments"),
    ("sublime-project", "JSON with Comments"),
    ("sublime-settings", "JSON with Comments"),
    ("sublime-snippet", "XML"),
    ("sublime-syntax", "YAML"),
    ("sublime-theme", "JSON with Comments"),
    ("sublime-workspace", "JSON with Comments"),
    ("surql", "SurrealQL"),
    ("sv", "SystemVerilog"),
    ("svelte", "Svelte"),
    ("svg", "SVG"),
    ("svh", "SystemVerilog"),
    ("svx", "Survex data"),
    ("sw", "XML"),
    ("swift", "Swift"),
    ("syntax", "YAML"),
    ("t", "Perl"),
    ("tab", "SQL"),
    ("tac", "Python"),
    ("tact", "JSON"),
    ("tag", "Java Server Pages"),
    ("talon", "Talon"),
    ("targets", "XML"),
    ("tcc", "C++"),
    ("tcl", "Tcl"),
    ("tcl.in", "Tcl"),
    ("templ", "templ"),
    ("tesc", "GLSL"),
    ("tese", "GLSL"),
    ("tex", "TeX"),
    ("textgrid", "TextGrid"),
    ("textile", "Textile"),
    ("tf", "HCL"),
    ("tfstate", "JSON"),
    ("tfstate.backup", "JSON"),
    ("tftpl", "Terraform Template"),
    ("tfvars", "HCL"),
    ("thor", "Ruby"),
    ("thrift", "Thrift"),
    ("thy", "Isabelle"),
    ("tl", "Teal"),
    ("tla", "TLA"),
    ("tlv", "TL-Verilog"),
    ("tm", "Tcl"),
    ("tmac", "Roff"),
    ("tmcommand", "XML Property List"),
    ("tmdl", "TMDL"),
    ("tml", "XML"),
    ("tmlanguage", "XML Property List"),
    ("tmpl", "Go Template"),
    ("tmpreferences", "XML Property List"),
    ("tmsnippet", "XML Property List"),
    ("tmtheme", "XML Property List"),
    ("tmux", "Shell"),
    ("toc", "TeX"),
    ("tofu", "HCL"),
    ("toit", "Toit"),
    ("toml", "TOML"),
    ("toml.example", "TOML"),
    ("tool", "Shell"),
    ("topojson", "JSON"),
    ("tpb", "PLSQL"),
    ("tpl", "Go Template"),
    ("tpp", "C++"),
    ("tps", "PLSQL"),
    ("tres", "Godot Resource"),
    ("trg", "PLSQL"),
    ("trigger", "Shell"),
    ("ts", "TypeScript"),
    ("tscn", "Godot Resource"),
    ("tsconfig.json", "JSON with Comments"),
    ("tsp", "TypeSpec"),
    ("tst", "GAP"),
    ("tsv", "TSV"),
    ("tsx", "TypeScript"),
    ("tu", "Turing"),
    ("twig", "Twig"),
    ("txl", "TXL"),
    ("txt", "Adblock Filter List"),
    ("txx", "C++"),
    ("typ", "XML"),
    ("uc", "UnrealScript"),
    ("udf", "SQL"),
    ("udo", "Csound"),
    ("ui", "XML"),
    ("unity", "Unity3D Asset"),
    ("uno", "Uno"),
    ("upc", "Unified Parallel C"),
    ("uplc", "Untyped Plutus Core"),
    ("ur", "UrWeb"),
    ("urdf", "XML"),
    ("url", "INI"),
    ("urs", "UrWeb"),
    ("ux", "XML"),
    ("v", "Verilog"),
    ("vala", "Vala"),
    ("vapi", "Vala"),
    ("vark", "Gosu"),
    ("vb", "Visual Basic .NET"),
    ("vba", "Vim Script"),
    ("vbhtml", "Visual Basic .NET"),
    ("vbproj", "XML"),
    ("vbs", "VBScript"),
    ("vcf", "TSV"),
    ("vcl", "VCL"),
    ("vcxproj", "XML"),
    ("vdf", "Valve Data Format"),
    ("veo", "Verilog"),
    ("vert", "GLSL"),
    ("vh", "SystemVerilog"),
    ("vhd", "VHDL"),
    ("vhdl", "VHDL"),
    ("vhf", "VHDL"),
    ("vhi", "VHDL"),
    ("vho", "VHDL"),
    ("vhost", "ApacheConf"),
    ("vhs", "VHDL"),
    ("vht", "VHDL"),
    ("vhw", "VHDL"),
    ("vim", "Vim Script"),
    ("vimrc", "Vim Script"),
    ("viw", "SQL"),
    ("vmb", "Vim Script"),
    ("volt", "Volt"),
    ("vrx", "GLSL"),
    ("vs", "GLSL"),
    ("vsh", "GLSL"),
    ("vshader", "GLSL"),
    ("vsixmanifest", "XML"),
    ("vssettings", "XML"),
    ("vstemplate", "XML"),
    ("vtl", "Velocity Template Language"),
    ("vto", "Vento"),
    ("vue", "Vue"),
    ("vw", "PLSQL"),
    ("vxml", "XML"),
    ("vy", "Vyper"),
    ("w", "CWeb"),
    ("wast", "WebAssembly"),
    ("wat", "WebAssembly"),
    ("watchr", "Ruby"),
    ("wdl", "WDL"),
    ("webapp", "JSON"),
    ("webmanifest", "JSON"),
    ("wgsl", "WGSL"),
    ("whiley", "Whiley"),
    ("wiki", "Wikitext"),
    ("wikitext", "Wikitext"),
    ("wisp", "wisp"),
    ("wit", "WebAssembly Interface Type"),
    ("wixproj", "XML"),
    ("wl", "Wolfram Language"),
    ("wlk", "Wollok"),
    ("wls", "Wolfram Language"),
    ("wlt", "Wolfram Language"),
    ("wlua", "Lua"),
    ("workbook", "Markdown"),
    ("workflow", "XML"),
    ("wren", "Wren"),
    ("ws", "Witcher Script"),
    ("wsdl", "XML"),
    ("wsf", "XML"),
    ("wsgi", "Python"),
    ("wxi", "XML"),
    ("wxl", "XML"),
    ("wxs", "XML"),
    ("x", "DirectX 3D File"),
    ("x10", "X10"),
    ("x3d", "XML"),
    ("x68", "Motorola 68K Assembly"),
    ("xacro", "XML"),
    ("xaml", "XML"),
    ("xc", "XC"),
    ("xdc", "Tcl"),
    ("xht", "HTML"),
    ("xhtml", "HTML"),
    ("xib", "XML"),
    ("xlf", "XML"),
    ("xliff", "XML"),
    ("xmi", "XML"),
    ("xml", "XML"),
    ("xml.dist", "XML"),
    ("xmp", "XML"),
    ("xojo_code", "Xojo"),
    ("xojo_menu", "Xojo"),
    ("xojo_report", "Xojo"),
    ("xojo_script", "Xojo"),
    ("xojo_toolbar", "Xojo"),
    ("xojo_window", "Xojo"),
    ("xproj", "XML"),
    ("xpy", "Python"),
    ("xq", "XQuery"),
    ("xql", "XQuery"),
    ("xqm", "XQuery"),
    ("xquery", "XQuery"),
    ("xqy", "XQuery"),
    ("xrl", "Erlang"),
    ("xsd", "XML"),
    ("xsh", "Xonsh"),
    ("xsjs", "JavaScript"),
    ("xsjslib", "JavaScript"),
    ("xsl", "XSLT"),
    ("xslt", "XSLT"),
    ("xspec", "XML"),
    ("xtend", "Xtend"),
    ("xul", "XML"),
    ("xzap", "ZAP"),
    ("y", "Yacc"),
    ("yacc", "Yacc"),
    ("yaml", "YAML"),
    ("yaml-tmlanguage", "YAML"),
    ("yaml.sed", "YAML"),
    ("yap", "Prolog"),
    ("yar", "YARA"),
    ("yara", "YARA"),
    ("yasnippet", "YASnippet"),
    ("yml", "YAML"),
    ("yml.mysql", "YAML"),
    ("yrl", "Erlang"),
    ("yul", "Yul"),
    ("yy", "JSON"),
    ("yyp", "JSON"),
    ("zap", "ZAP"),
    ("zcml", "XML"),
    ("zep", "Zephir"),
    ("zig", "Zig"),
    ("zig.zon", "Zig"),
    ("zil", "ZIL"),
    ("zimpl", "Zimpl"),
    ("zmodel", "Zmodel"),
    ("zmpl", "Zimpl"),
    ("zpl", "Zimpl"),
    ("zs", "ZenScript"),
    ("zsh", "Shell"),
    ("zsh-theme", "Shell"),
];

pub const NAME_TO_LANG: &[(&str, &str)] = &[
    ("_emacs", "Emacs Lisp"),
    ("_helpers.tpl", "Go Template"),
    ("_vimrc", "Vim Script"),
    (".abbrev_defs", "Emacs Lisp"),
    (".ackrc", "Option List"),
    (".all-contributorsrc", "JSON"),
    (".arcconfig", "JSON"),
    (".atomignore", "Ignore List"),
    (".auto-changelog", "JSON"),
    (".babelignore", "Ignore List"),
    (".babelrc", "JSON with Comments"),
    (".bash_aliases", "Shell"),
    (".bash_functions", "Shell"),
    (".bash_history", "Shell"),
    (".bash_logout", "Shell"),
    (".bash_profile", "Shell"),
    (".bashrc", "Shell"),
    (".browserslistrc", "Browserslist"),
    (".buckconfig", "INI"),
    (".bzrignore", "Ignore List"),
    (".c8rc", "JSON"),
    (".clang-format", "YAML"),
    (".clang-tidy", "YAML"),
    (".clangd", "YAML"),
    (".classpath", "XML"),
    (".coffeelintignore", "Ignore List"),
    (".coveragerc", "INI"),
    (".cproject", "XML"),
    (".cshrc", "Shell"),
    (".cvsignore", "Ignore List"),
    (".devcontainer.json", "JSON with Comments"),
    (".dockerignore", "Ignore List"),
    (".easignore", "Ignore List"),
    (".editorconfig", "EditorConfig"),
    (".eleventyignore", "Ignore List"),
    (".emacs", "Emacs Lisp"),
    (".emacs.desktop", "Emacs Lisp"),
    (".env", "Dotenv"),
    (".env.ci", "Dotenv"),
    (".env.dev", "Dotenv"),
    (".env.development", "Dotenv"),
    (".env.development.local", "Dotenv"),
    (".env.example", "Dotenv"),
    (".env.local", "Dotenv"),
    (".env.prod", "Dotenv"),
    (".env.production", "Dotenv"),
    (".env.sample", "Dotenv"),
    (".env.staging", "Dotenv"),
    (".env.template", "Dotenv"),
    (".env.test", "Dotenv"),
    (".env.testing", "Dotenv"),
    (".envrc", "Shell"),
    (".eslintignore", "Ignore List"),
    (".eslintrc.json", "JSON with Comments"),
    (".exrc", "Vim Script"),
    (".factor-boot-rc", "Factor"),
    (".factor-rc", "Factor"),
    (".flake8", "INI"),
    (".flaskenv", "Shell"),
    (".gclient", "Python"),
    (".gemrc", "YAML"),
    (".git-blame-ignore-revs", "Git Revision List"),
    (".gitattributes", "Git Attributes"),
    (".gitconfig", "Git Config"),
    (".gitignore", "Ignore List"),
    (".gitmodules", "Git Config"),
    (".gnus", "Emacs Lisp"),
    (".gvimrc", "Vim Script"),
    (".htaccess", "ApacheConf"),
    (".htmlhintrc", "JSON"),
    (".ignore", "Ignore List"),
    (".imgbotconfig", "JSON"),
    (".irbrc", "Ruby"),
    (".jscsrc", "JSON with Comments"),
    (".jshintrc", "JSON with Comments"),
    (".jslintrc", "JSON with Comments"),
    (".justfile", "Just"),
    (".kshrc", "Shell"),
    (".latexmkrc", "Perl"),
    (".login", "Shell"),
    (".luacheckrc", "Lua"),
    (".markdownlintignore", "Ignore List"),
    (".nanorc", "nanorc"),
    (".nodemonignore", "Ignore List"),
    (".npmignore", "Ignore List"),
    (".npmrc", "NPM Config"),
    (".nvimrc", "Vim Script"),
    (".nycrc", "JSON"),
    (".oxlintrc.json", "JSON with Comments"),
    (".php", "PHP"),
    (".php_cs", "PHP"),
    (".php_cs.dist", "PHP"),
    (".prettierignore", "Ignore List"),
    (".profile", "Shell"),
    (".project", "XML"),
    (".pryrc", "Ruby"),
    (".pylintrc", "INI"),
    (".rprofile", "R"),
    (".rspec", "Option List"),
    (".scalafix.conf", "HOCON"),
    (".scalafmt.conf", "HOCON"),
    (".shellcheckrc", "ShellCheck Config"),
    (".simplecov", "Ruby"),
    (".spacemacs", "Emacs Lisp"),
    (".stylelintignore", "Ignore List"),
    (".swcrc", "JSON with Comments"),
    (".tern-config", "JSON"),
    (".tern-project", "JSON"),
    (".tm_properties", "TextMate Properties"),
    (".tmux.conf", "Shell"),
    (".vercelignore", "Ignore List"),
    (".vimrc", "Vim Script"),
    (".viper", "Emacs Lisp"),
    (".vscodeignore", "Ignore List"),
    (".watchmanconfig", "JSON"),
    (".xinitrc", "Shell"),
    (".xsession", "Shell"),
    (".yardopts", "Option List"),
    (".zlogin", "Shell"),
    (".zlogout", "Shell"),
    (".zprofile", "Shell"),
    (".zshenv", "Shell"),
    (".zshrc", "Shell"),
    ("9fs", "Shell"),
    ("abbrev_defs", "Emacs Lisp"),
    ("ack", "Perl"),
    ("ackrc", "Option List"),
    ("ant.xml", "Ant Build System"),
    ("apache2.conf", "ApacheConf"),
    ("api-extractor.json", "JSON with Comments"),
    ("apkbuild", "Alpine Abuild"),
    ("app.config", "XML"),
    ("appraisals", "Ruby"),
    ("bash_aliases", "Shell"),
    ("bash_logout", "Shell"),
    ("bash_profile", "Shell"),
    ("bashrc", "Shell"),
    ("berksfile", "Ruby"),
    ("brewfile", "Ruby"),
    ("browserslist", "Browserslist"),
    ("bsdmakefile", "Makefile"),
    ("buck", "Starlark"),
    ("build", "Starlark"),
    ("build.bazel", "Starlark"),
    ("build.xml", "Ant Build System"),
    ("buildfile", "Ruby"),
    ("buildozer.spec", "INI"),
    ("bun.lock", "JSON"),
    ("cabal.config", "Cabal Config"),
    ("cabal.project", "Cabal Config"),
    ("caddyfile", "Caddyfile"),
    ("cakefile", "CoffeeScript"),
    ("capfile", "Ruby"),
    ("cargo.lock", "TOML"),
    ("cargo.toml.orig", "TOML"),
    ("cask", "Emacs Lisp"),
    ("citation.cff", "YAML"),
    ("cmakelists.txt", "CMake"),
    ("commit_editmsg", "Git Commit"),
    ("composer.lock", "JSON"),
    ("containerfile", "Dockerfile"),
    ("contents.lr", "Markdown"),
    ("cpanfile", "Perl"),
    ("crontab", "crontab"),
    ("cshrc", "Shell"),
    ("dangerfile", "Ruby"),
    ("deliverfile", "Ruby"),
    ("deno.lock", "JSON"),
    ("deps", "Python"),
    ("dev-requirements.txt", "Pip Requirements"),
    ("devcontainer.json", "JSON with Comments"),
    ("dockerfile", "Dockerfile"),
    ("dune-project", "Dune"),
    ("earthfile", "Earthly"),
    ("eask", "Emacs Lisp"),
    ("emakefile", "Erlang"),
    ("eqnrc", "Roff"),
    ("expr-dist", "R"),
    ("fakefile", "Fancy"),
    ("fastfile", "Ruby"),
    ("firestore.rules", "Cloud Firestore Security Rules"),
    ("flake.lock", "JSON"),
    ("fp-lib-table", "KiCad Layout"),
    ("gemfile", "Ruby"),
    ("gemfile.lock", "Gemfile.lock"),
    ("gitignore_global", "Ignore List"),
    ("gitignore-global", "Ignore List"),
    ("glide.lock", "YAML"),
    ("gnumakefile", "Makefile"),
    ("go.mod", "Go Module"),
    ("go.sum", "Go Checksums"),
    ("go.work", "Go Workspace"),
    ("go.work.sum", "Go Checksums"),
    ("gopkg.lock", "TOML"),
    ("gradlew", "Shell"),
    ("gradlew.bat", "Batchfile"),
    ("guardfile", "Ruby"),
    ("gvimrc", "Vim Script"),
    ("haproxy.cfg", "HAProxy"),
    ("hosts", "Hosts File"),
    ("hosts.txt", "Hosts File"),
    ("httpd.conf", "ApacheConf"),
    ("installscript.qs", "Qt Script"),
    ("jakefile", "JavaScript"),
    ("jarfile", "Ruby"),
    ("jenkinsfile", "Groovy"),
    ("jsconfig.json", "JSON with Comments"),
    ("justfile", "Just"),
    ("kakrc", "KakouneScript"),
    ("kbuild", "Makefile"),
    ("kcl.mod", "KCL"),
    ("kcl.mod.lock", "KCL"),
    ("kshrc", "Shell"),
    ("language-configuration.json", "JSON with Comments"),
    ("language-subtag-registry.txt", "Record Jar"),
    ("latexmkrc", "Perl"),
    ("lexer.x", "Lex"),
    ("login", "Shell"),
    ("m3makefile", "Quake"),
    ("m3overrides", "Quake"),
    ("makefile", "Makefile"),
    ("makefile.am", "Makefile"),
    ("makefile.boot", "Makefile"),
    ("makefile.frag", "Makefile"),
    ("makefile.in", "Makefile"),
    ("makefile.inc", "Makefile"),
    ("makefile.pl", "Perl"),
    ("makefile.sco", "Makefile"),
    ("makefile.wat", "Makefile"),
    ("man", "Shell"),
    ("manifest.mf", "JAR Manifest"),
    ("mavenfile", "Ruby"),
    ("mcmod.info", "JSON"),
    ("meson_options.txt", "Meson"),
    ("meson.build", "Meson"),
    ("mix.lock", "Elixir"),
    ("mkfile", "Makefile"),
    ("mmn", "Roff"),
    ("mmt", "Roff"),
    ("mocha.opts", "Option List"),
    ("module.bazel", "Starlark"),
    ("module.bazel.lock", "JSON"),
    ("modulefile", "Puppet"),
    ("mvnw", "Shell"),
    ("mvnw.cmd", "Batchfile"),
    ("nanorc", "nanorc"),
    ("nextflow.config", "Nextflow"),
    ("nginx.conf", "Nginx"),
    ("nim.cfg", "Nim"),
    ("notebook", "Jupyter Notebook"),
    ("nuget.config", "XML"),
    ("nukefile", "Nu"),
    ("nvimrc", "Vim Script"),
    ("owh", "Tcl"),
    ("package.resolved", "JSON"),
    ("packages.config", "XML"),
    ("pdm.lock", "TOML"),
    ("phakefile", "PHP"),
    ("pipfile", "TOML"),
    ("pipfile.lock", "JSON"),
    ("pixi.lock", "YAML"),
    ("pkgbuild", "Shell"),
    ("podfile", "Ruby"),
    ("poetry.lock", "TOML"),
    ("procfile", "Procfile"),
    ("profile", "Shell"),
    ("project.ede", "Emacs Lisp"),
    ("project.godot", "Godot Resource"),
    ("puppetfile", "Ruby"),
    ("pylintrc", "INI"),
    ("rakefile", "Ruby"),
    ("rebar.config", "Erlang"),
    ("rebar.config.lock", "Erlang"),
    ("rebar.lock", "Erlang"),
    ("requirements-dev.txt", "Pip Requirements"),
    ("requirements.lock.txt", "Pip Requirements"),
    ("requirements.txt", "Pip Requirements"),
    ("rexfile", "Perl"),
    ("riemann.config", "Clojure"),
    ("root", "Isabelle ROOT"),
    ("sconscript", "Python"),
    ("sconstruct", "Python"),
    ("settings.stylecop", "XML"),
    ("singularity", "Singularity"),
    ("slakefile", "LiveScript"),
    ("snakefile", "Snakemake"),
    ("snapfile", "Ruby"),
    ("starfield", "Tcl"),
    ("steepfile", "Ruby"),
    ("suite.rc", "Cylc"),
    ("thorfile", "Ruby"),
    ("tiltfile", "Starlark"),
    ("tmux.conf", "Shell"),
    ("toolchain_installscript.qs", "Qt Script"),
    ("torrc", "Tor Config"),
    ("troffrc", "Roff"),
    ("troffrc-end", "Roff"),
    ("tsconfig.json", "JSON with Comments"),
    ("tslint.json", "JSON with Comments"),
    ("uv.lock", "TOML"),
    ("vagrantfile", "Ruby"),
    ("vimrc", "Vim Script"),
    ("vlcrc", "INI"),
    ("web.config", "XML"),
    ("web.debug.config", "XML"),
    ("web.release.config", "XML"),
    ("workspace", "Starlark"),
    ("workspace.bazel", "Starlark"),
    ("workspace.bzlmod", "Starlark"),
    ("wscript", "Python"),
    ("xinitrc", "Shell"),
    ("xmake.lua", "Xmake"),
    ("xsession", "Shell"),
    ("yarn.lock", "YAML"),
    ("zlogin", "Shell"),
    ("zlogout", "Shell"),
    ("zprofile", "Shell"),
    ("zshenv", "Shell"),
    ("zshrc", "Shell"),
];
